

services:
  php-env:
    build: .
    container_name: 'yuri_app_server'
    volumes:
      - ./src:/var/www/html
    ports:
      - 9000:80
  mysql_db:
    image: mysql:latest
    container_name: 'yuri_db_server'
    environment:
      MYSQL_ROOT_PASSWORD: root
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: 'yuri_dbms_software'
    environment:
      PMA_HOST: mysql_db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - 9001:80
